- name: Ensure Python 3.11 is installed
  ansible.builtin.package:
    name: python3.11,python3.11-pip

- name: Check if pipx is installed
  ansible.builtin.shell:
    cmd: which pipx; echo -n $?
  register: pipx_exists

- name: Install pipx
  when: pipx_exists.stdout == "1"
  ansible.builtin.pip:
    name: pipx

- name: Install pipx to global path
  when: pipx_exists.stdout == "1"
  ansible.builtin.shell:
    cmd: python3 -m pipx ensurepath --global

- name: Ensure ssm-user exists and keep groups
  ansible.builtin.user:
    name: ssm-user
    state: present
    groups: sudo
    append: yes
    
- name: Create /usr/share/ssm-user directory
  ansible.builtin.file:
    path: /usr/share/ssm-user
    state: directory
    owner: ssm-user
    group: ssm-user
    mode: '0755'